### ISSUE TITLE
建议给./增加判断或者将trash脚本中$FileName.$1中的.替换其他分隔符

### ISSUE THREAD

**Issue by skinnyshy** [LIU-LIU-LIU/Recycle_bin#2]
例如当执行`rm ./99_99.txt`删除当前目录下的`99_99.txt`文件时
![image](https://user-images.githubusercontent.com/12553514/70103710-d7299500-1676-11ea-8fae-e53d75a3ec3a.png)

**Comment by LIU-LIU-LIU** [comment]
收到，我做个判断。

**Comment by LIU-LIU-LIU** [comment]
好久之前的东西，今天被你一提突然想改改。现在问题全部修复了，还加了一些功能 可以像原生rm那样随心删了。
